import { create } from "zustand";
import { useI18n, type CopyKey, type Locale } from "@/lib/i18n";

export type DisplayLanguage = Locale | "ja" | "ko";

type UiDictionary = Partial<Record<CopyKey, string>>;

const JA: UiDictionary = {
  brand: "昭梧",
  tagline: "まだ見えない兆しを照らし、帰る場所を見つける",
  manifesto: "まだ見えない兆しを照らし、帰る場所を見つける。",
  introAria: "昭梧を読み込んでいます",
  introLoadingAuth: "アカウントとレポートを読み込んでいます",
  introLoadingPage: "ページを準備しています",
  introSkip: "アニメーションをスキップ",
  heroKicker: "命理 · 時機 · 選択",
  heroSlogan: "まだ見えない兆しを照らし、帰る場所を見つける。",
  heroLead: "命を知ることは、運命に従うことではありません。見通したうえで、どこへ進むかを知ることです。",
  heroBody: "昭梧は命理を鏡として、時を読み、勢いを見極め、進む道を整理します。まだ形になっていない兆しを捉え、一つひとつの選択に落ち着ける場所をつくります。",
  heroEnglish: "See what lies unseen. Find where you belong.",
  heroSign: "勢いを読む · 時を知る · 帰る場所を得る",
  m1: "命理は宿命論ではなく、自分の傾向を理解するための方法です。",
  m2: "運勢は答えではなく、好機を見抜くための手がかりです。",
  m3: "人生を変えるのは、最後には一つひとつの意識的な選択です。",
  product: "人生の流れと選択の分析",
  start: "分析を始める",
  navHome: "ホーム",
  navMine: "マイ昭梧",
  navLogin: "ログイン",
  navAdmin: "管理",
  logout: "ログアウト",
  language: "言語",
  today: "今日の昭梧",
  todayStem: "今日の干支",
  todayTheme: "今日のテーマ",
  yi: "吉",
  ji: "避けたいこと",
  jieqi: "節気",
  chong: "冲",
  sha: "煞方",
  lunar: "旧暦",
  formTitle: "四柱推命（八字）",
  formLead: "出生証明に記載された日付・時刻・都市を入力してください。残りはシステムが計算します。",
  question: "今、いちばん知りたいことは何ですか？",
  qPh: "例：この仕事を続けるべき？ 今、何を最優先にすべき？",
  year: "年",
  month: "月",
  day: "日",
  time: "出生時刻",
  timeUnknown: "時刻が不明 — 時柱と命宮は空欄にします",
  gender: "性別（大運計算用）",
  male: "男性",
  female: "女性",
  unset: "回答しない",
  relation: "恋愛対象の傾向",
  relAny: "指定なし",
  relHet: "異性",
  relSame: "同性／多様",
  relHint: "恋愛に関する質問の方向づけにのみ使い、他の分析には影響しません。",
  city: "出生地（都市／国）",
  cityPh: "出生した都市と国を入力",
  popularCities: "よく使う都市",
  liveCity: "現在の居住都市（任意）",
  optional: "任意",
  liveHint: "南北半球・季節・生活リズムの補足にのみ使い、出生八字は変更しません。",
  hourPh: "時 0–23",
  minutePh: "分 0–59",
  solar: "真太陽時補正を適用",
  zi: "子刻の日付切替",
  ziLate: "23時から翌日として扱う",
  ziMid: "日付は0時に切り替える",
  analyze: "分析を始める",
  analyzing: "命盤を作成しています…",
  locating: "出生地の時刻を換算しています…",
  remembered: "前回保存した出生情報を読み込みました。必要なら編集できます。",
  errCity: "検索結果から出生都市と国を選択してください。",
  errQuestion: "まず、本当に知りたい質問を書いてください。",
  errAnalyze: "分析を完了できませんでした。入力内容を確認して、もう一度お試しください。",
  faq: "よくある質問",
  faq1q: "分析は何を根拠にしていますか？",
  faq1a: "昭梧は伝統的な子平八字を唯一の主判とします。前世／六道の質問は達摩一掌経の確定的な排盤を使用し、追加のAI推測は行いません。",
  faq2q: "分析結果は必ず当たりますか？",
  faq2a: "出来事の発生を保証するものではありません。八字は構造・時機・起こりやすい課題を整理するためのもので、現実の資源・選択・行動によって結果は変わります。",
  faq3q: "データは保存されますか？",
  faq3a: "ログインするとレポートを「マイ昭梧」に保存できます。ログアウト状態の分析は現在の閲覧中だけ保持されます。",
  resultQ: "あなたの分析",
  resultA: "結論",
  chart: "あなたの四柱八字",
  dayMaster: "日主（日干）",
  monthLing: "月令",
  nayin: "納音",
  shishen: "十神",
  hide: "蔵干",
  dishi: "十二運",
  xunkong: "空亡（旬空）",
  wuxing: "旺衰の基礎",
  favorEl: "流れを整える暫定候補",
  drainEl: "今は強めすぎない要素",
  useful: "流れを整える暫定候補（要確認）",
  drain: "今は強めすぎない要素（要確認）",
  strength: "旺衰の基礎",
  dayun: "大運の流れ",
  rhythm: "人生全体のリズム",
  life: "生活での使い方",
  work: "仕事",
  love: "恋愛・関係",
  money: "金銭",
  body: "心身",
  home: "住まい",
  action: "最優先の行動",
  guide: "色・方位・時間帯",
  favor: "比較的追い風",
  rest: "今は強調しすぎない",
  pet: "ペットの象意",
  provenance: "排盤の根拠",
  full: "わかりやすい完全レポート",
  genFull: "完全レポートを見る",
  generating: "完全レポートを整理しています…",
  save: "マイ昭梧に保存",
  saved: "保存済み",
  needLogin: "ログインすると保存して続きから読めます。",
  reset: "最初からやり直す",
  disclaimer: "これは伝統文化と象徴的解釈に基づき、人生の傾向や課題を理解するためのものです。医療・法律・金融上の判断に代わるものではありません。",
  mineLead: "同じアカウントに出生情報、これまでの質問、完全レポートを保存できます。",
  emptyMine: "まだレポートがありません。分析を完了すると、ここに保存できます。",
  open: "開く",
  del: "削除",
  loginTitle: "昭梧にログイン",
  loginLead: "ログインすると完全レポートを「マイ昭梧」に保存できます。",
  loginPageLead: "ログインすると出生情報と最近のレポートを保存できます。オーナーアカウントでは、顧客ごとの利用可能な最新レポートを確認できます。",
  loginTab: "ログイン",
  signupTab: "新規登録",
  signupTitle: "昭梧アカウントを作成",
  displayName: "お名前",
  displayNamePh: "呼び名を入力",
  password: "パスワード",
  passwordPh: "8文字以上",
  processing: "処理中…",
  createAccount: "アカウントを作成",
  loginUnavailable: "ログインサービスはまだ設定されていません。",
  loginValidation: "有効なメールアドレスと8文字以上のパスワードを入力してください。",
  accountCreated: "アカウントを作成しました。メール認証を完了してから、こちらに戻ってログインしてください。",
  invalidCredentials: "メールアドレスまたはパスワードが正しくありません。",
  loginFailed: "ログインに失敗しました。",
  loggedInTitle: "昭梧にログイン済み",
  enterMine: "マイ昭梧を開く",
  owner: "オーナー",
  withGoogle: "Googleで続ける",
  withApple: "Appleで続ける",
  withX: "Xで続ける",
  orEmail: "またはメールアドレスを使用",
  backHome: "ホームへ戻る",
  steps: "3ステップ。命理の予備知識は不要です",
  s1: "本当に知りたい質問を書く",
  s2: "出生年月日・時刻・都市を入力",
  s3: "まず結論を読み、その後に完全レポートを確認",
  accountAdmin: "アカウント／管理",
  methodKicker: "方法は透明 · 境界は明確",
  methodTitle: "何が計算でき、何が計算できないかを先に明確にします",
  methodLead: "昭梧は、接続済みの方法、未接続のデータ、判断の境界を明示します。見栄えの良い言葉を結論の代わりにはしません。",
  proofPrimaryTitle: "子平法を主判に",
  proofPrimaryBody: "子平八字を唯一の中心判断として、まず質問に答え、その後に命盤と根拠を示します。",
  proofPastTitle: "前世は独立排盤",
  proofPastBody: "六道／前世の質問は達摩一掌経の確定的な排盤だけを使い、追加のAI推測は行いません。",
  galleryKicker: "単独ツール",
  galleryTitle: "1ページに1つの明確な目的",
  galleryBody: "独立して使える排盤やテストをまとめています。各ページは用途・入力・結果だけを表示し、完全レポートの流れとは分けています。",
  palmToolKicker: "無料ツール · AI不使用",
  palmToolTitle: "達摩一掌経｜四宮と六道",
  palmToolBody: "出生年月日・時刻・伝統的な順逆を入力すると、年・月・日・時の四宮を確認できます。端末内で計算し、ログインも保存も不要です。",
  palmToolScope: "用途｜前四世の四宮、十二星、六道の習気、本命の主軸を確認",
  palmToolButton: "無料排盤を始める",
  proofBoundaryTitle: "未接続のものは推測しない",
  proofBoundaryBody: "紫微斗数・西洋占星術・六爻などは、独立した排盤が接続されるまで未接続として明示します。",
  myTitle: "マイ昭梧",
  mySignedOutLead: "ログインすると出生情報と最近3件のレポートを確認できます。",
  followTitle: "この命盤で続けて質問する",
  followGuestLead: "ログインすると同じ命盤を再利用でき、出生情報を再入力する必要はありません。",
  followLead: "四柱・月令・真太陽時・大運は現在の命盤をそのまま使い、新しい質問だけを改めて判断します。",
  followLogin: "ログインして続ける",
  followButton: "続けて質問",
  followBusy: "分析中…",
  followPh: "例：今は転職を先にすべき？ それとも今の仕事を終わらせるべき？",
  followError: "追加質問の分析に失敗しました。",
  guest: "ゲスト",
};

const KO: UiDictionary = {
  brand: "昭梧",
  tagline: "보이지 않는 징조를 밝히고, 돌아갈 자리를 찾다",
  manifesto: "보이지 않는 징조를 밝히고, 돌아갈 자리를 찾다.",
  introAria: "昭梧를 불러오는 중입니다",
  introLoadingAuth: "계정과 보고서 정보를 불러오는 중입니다",
  introLoadingPage: "페이지를 준비하는 중입니다",
  introSkip: "애니메이션 건너뛰기",
  heroKicker: "명리 · 시기 · 선택",
  heroSlogan: "보이지 않는 징조를 밝히고, 돌아갈 자리를 찾다.",
  heroLead: "운명을 안다는 것은 운명에 굴복하는 일이 아닙니다. 흐름을 본 뒤 어디로 갈지 아는 일입니다.",
  heroBody: "昭梧는 명리를 거울로 삼아 때를 보고, 흐름을 살피고, 길을 정리합니다. 아직 드러나지 않은 징조를 읽고 매 선택마다 머물 수 있는 자리를 남깁니다.",
  heroEnglish: "See what lies unseen. Find where you belong.",
  heroSign: "흐름을 보고 · 때를 알고 · 돌아갈 자리를 찾다",
  m1: "명리는 숙명론이 아니라 자신의 패턴을 이해하는 방법입니다.",
  m2: "운세는 정답이 아니라 기회를 알아보는 능력입니다.",
  m3: "인생을 실제로 바꾸는 것은 결국 매 순간의 의식적인 선택입니다.",
  product: "인생 흐름과 선택 분석",
  start: "내 분석 시작하기",
  navHome: "홈",
  navMine: "나의 昭梧",
  navLogin: "로그인",
  navAdmin: "관리",
  logout: "로그아웃",
  language: "언어",
  today: "오늘의 昭梧",
  todayStem: "오늘의 간지",
  todayTheme: "오늘의 주제",
  yi: "좋은 일",
  ji: "피할 일",
  jieqi: "절기",
  chong: "충",
  sha: "살방",
  lunar: "음력",
  formTitle: "사주팔자",
  formLead: "출생증명서에 적힌 날짜, 시간, 도시를 입력하세요. 나머지는 시스템이 계산합니다.",
  question: "지금 가장 알고 싶은 것은 무엇인가요?",
  qPh: "예: 이 일을 계속해야 할까요? 지금 무엇을 먼저 처리해야 할까요?",
  year: "년",
  month: "월",
  day: "일",
  time: "출생 시간",
  timeUnknown: "시간 불확실 — 시주와 명궁은 비워 둡니다",
  gender: "성별(대운 계산용)",
  male: "남성",
  female: "여성",
  unset: "선택하지 않음",
  relation: "연애 대상 성향",
  relAny: "제한 없음",
  relHet: "이성",
  relSame: "동성／다양성",
  relHint: "연애 질문의 방향을 정하는 데만 사용하며 다른 분석에는 영향을 주지 않습니다.",
  city: "출생 도시／국가",
  cityPh: "출생 도시와 국가를 입력하세요",
  popularCities: "자주 쓰는 도시",
  liveCity: "현재 거주 도시(선택)",
  optional: "선택",
  liveHint: "남북반구, 계절, 생활 리듬 보정에만 쓰며 출생 사주 자체는 바꾸지 않습니다.",
  hourPh: "시 0–23",
  minutePh: "분 0–59",
  solar: "진태양시 보정 적용",
  zi: "자시 날짜 기준",
  ziLate: "23시부터 다음 날로 계산",
  ziMid: "자정(00:00)에 날짜 변경",
  analyze: "분석 시작",
  analyzing: "명식을 만드는 중…",
  locating: "출생지 시간을 보정하는 중…",
  remembered: "이전에 저장한 출생 정보를 불러왔습니다. 바로 수정할 수 있습니다.",
  errCity: "검색 결과에서 출생 도시와 국가를 선택하세요.",
  errQuestion: "먼저 정말 알고 싶은 질문을 적어 주세요.",
  errAnalyze: "분석을 완료하지 못했습니다. 입력 정보를 확인한 뒤 다시 시도해 주세요.",
  faq: "자주 묻는 질문",
  faq1q: "분석은 무엇을 기준으로 하나요?",
  faq1a: "昭梧는 전통 자평 사주를 유일한 주판으로 사용합니다. 전생／육도 질문은 달마일장경(達摩一掌經)의 확정식 계산만 사용하며 추가 AI 추측은 하지 않습니다.",
  faq2q: "분석 결과는 반드시 맞나요?",
  faq2a: "어떤 사건의 발생도 보장하지 않습니다. 사주는 구조, 시기, 가능성이 높은 과제를 정리하는 도구이며 현실의 자원, 선택, 행동에 따라 결과는 달라집니다.",
  faq3q: "내 정보는 저장되나요?",
  faq3a: "로그인하면 보고서를 ‘나의 昭梧’에 저장할 수 있습니다. 로그아웃 상태의 분석은 현재 방문 중에만 유지됩니다.",
  resultQ: "분석 결과",
  resultA: "직답",
  chart: "나의 사주팔자",
  dayMaster: "일간（日主）",
  monthLing: "월령",
  nayin: "납음",
  shishen: "십신",
  hide: "지장간",
  dishi: "십이운성",
  xunkong: "공망（旬空）",
  wuxing: "신강·신약 기초",
  favorEl: "흐름을 돕는 임시 후보",
  drainEl: "지금은 키우지 않을 요소",
  useful: "흐름을 돕는 임시 후보(재검토 필요)",
  drain: "지금은 키우지 않을 요소(재검토 필요)",
  strength: "신강·신약 기초",
  dayun: "대운 흐름",
  rhythm: "전체 인생 리듬",
  life: "생활 적용",
  work: "일／직업",
  love: "연애／관계",
  money: "재정",
  body: "몸과 마음",
  home: "주거／가정",
  action: "가장 우선할 행동",
  guide: "색상·방향·시간대",
  favor: "상대적으로 유리",
  rest: "지금은 과하게 키우지 않기",
  pet: "반려동물 상징",
  provenance: "명식 산출 근거",
  full: "쉬운 말 전체 보고서",
  genFull: "전체 보고서 보기",
  generating: "전체 보고서를 정리하는 중…",
  save: "나의 昭梧에 저장",
  saved: "저장됨",
  needLogin: "로그인하면 저장하고 이어서 볼 수 있습니다.",
  reset: "처음부터 다시",
  disclaimer: "전통문화와 상징적 해석을 바탕으로 삶의 패턴과 과제를 이해하기 위한 내용입니다. 의료·법률·재정 판단을 대신하지 않습니다.",
  mineLead: "한 계정에 출생 정보, 이전 질문, 전체 보고서를 저장할 수 있습니다.",
  emptyMine: "아직 저장된 보고서가 없습니다. 분석을 마치면 여기에 저장할 수 있습니다.",
  open: "열기",
  del: "삭제",
  loginTitle: "昭梧 로그인",
  loginLead: "로그인하면 전체 보고서를 ‘나의 昭梧’에 저장할 수 있습니다.",
  loginPageLead: "로그인하면 출생 정보와 최근 보고서를 저장할 수 있습니다. 소유자 계정에서는 고객별로 이용 가능한 최신 보고서를 확인할 수 있습니다.",
  loginTab: "로그인",
  signupTab: "회원가입",
  signupTitle: "昭梧 계정 만들기",
  displayName: "이름／호칭",
  displayNamePh: "어떻게 불러드릴까요?",
  password: "비밀번호",
  passwordPh: "8자 이상",
  processing: "처리 중…",
  createAccount: "계정 만들기",
  loginUnavailable: "로그인 서비스가 아직 설정되지 않았습니다.",
  loginValidation: "올바른 이메일과 8자 이상의 비밀번호를 입력하세요.",
  accountCreated: "계정이 만들어졌습니다. 이메일 인증을 완료한 뒤 다시 돌아와 로그인하세요.",
  invalidCredentials: "이메일 또는 비밀번호가 올바르지 않습니다.",
  loginFailed: "로그인에 실패했습니다.",
  loggedInTitle: "昭梧 로그인 완료",
  enterMine: "나의 昭梧 열기",
  owner: "소유자",
  withGoogle: "Google로 계속",
  withApple: "Apple로 계속",
  withX: "X로 계속",
  orEmail: "또는 이메일 사용",
  backHome: "홈으로 돌아가기",
  steps: "3단계면 충분합니다. 명리 지식은 필요하지 않습니다",
  s1: "정말 알고 싶은 질문을 적기",
  s2: "출생 날짜·시간·도시 입력",
  s3: "직답을 먼저 보고 전체 보고서 읽기",
  accountAdmin: "계정／관리",
  methodKicker: "방법은 투명하게 · 경계는 명확하게",
  methodTitle: "무엇을 계산할 수 있고 무엇을 계산할 수 없는지 먼저 밝힙니다",
  methodLead: "昭梧는 연결된 방법, 아직 연결되지 않은 자료, 판단의 경계를 공개합니다. 그럴듯한 문구를 결론처럼 쓰지 않습니다.",
  proofPrimaryTitle: "자평을 주판으로",
  proofPrimaryBody: "자평 사주를 유일한 핵심 판단으로 삼아 먼저 질문에 답하고 그 뒤 명식과 근거를 보여 줍니다.",
  proofPastTitle: "전생은 독립 계산",
  proofPastBody: "육도／전생 질문은 달마일장경(達摩一掌經)의 확정식 계산만 사용하고 추가 AI 추측은 하지 않습니다.",
  galleryKicker: "독립 도구",
  galleryTitle: "한 페이지에는 한 가지 목적만",
  galleryBody: "독립적으로 사용할 수 있는 명식과 테스트를 모았습니다. 각 페이지는 용도, 입력, 결과만 남기고 전체 보고서 흐름과 분리합니다.",
  palmToolKicker: "무료 도구 · AI 미사용",
  palmToolTitle: "달마일장경｜사궁과 육도",
  palmToolBody: "출생 날짜·시간과 전통 순역 기준을 입력하면 년·월·일·시의 사궁을 확인할 수 있습니다. 기기에서 계산하며 로그인이나 저장이 필요하지 않습니다.",
  palmToolScope: "용도｜전사세 사궁, 십이성, 육도 습기, 본명 주축 확인",
  palmToolButton: "무료 명식 시작",
  proofBoundaryTitle: "연결되지 않은 체계는 지어내지 않음",
  proofBoundaryBody: "자미두수, 서양 점성술, 육효 등은 자체 계산이 연결되기 전까지 ‘미연결’로 표시합니다.",
  myTitle: "나의 昭梧",
  mySignedOutLead: "로그인하면 출생 정보와 최근 보고서 3개를 볼 수 있습니다.",
  followTitle: "이 명식으로 계속 질문하기",
  followGuestLead: "로그인하면 같은 명식을 다시 입력하지 않고 이어서 질문할 수 있습니다.",
  followLead: "사주, 월령, 진태양시, 대운은 현재 명식을 그대로 쓰고 새 질문만 다시 판단합니다.",
  followLogin: "로그인하고 이어서 질문",
  followButton: "추가 질문",
  followBusy: "분석 중…",
  followPh: "예: 지금 이직을 먼저 해야 할까요, 아니면 현재 일을 마무리해야 할까요?",
  followError: "추가 질문 분석에 실패했습니다.",
  guest: "방문자",
};

const BASE_TRANSLATOR = useI18n.getState().t;

export function engineLocaleFor(language: DisplayLanguage): Locale {
  return language === "zh-Hant" || language === "zh-Hans" ? language : "en";
}

export function displayText(
  language: DisplayLanguage,
  hant: string,
  hans: string,
  en: string,
  ja: string,
  ko: string,
) {
  if (language === "ja") return ja;
  if (language === "ko") return ko;
  if (language === "en") return en;
  return language === "zh-Hans" ? hans : hant;
}

export function intlTagFor(language: DisplayLanguage) {
  if (language === "ja") return "ja-JP";
  if (language === "ko") return "ko-KR";
  if (language === "en") return "en-AU";
  return language === "zh-Hans" ? "zh-CN" : "zh-TW";
}

function readDisplayLanguage(): DisplayLanguage {
  if (typeof window === "undefined") return "zh-Hant";
  try {
    const value = window.localStorage.getItem("zhaowu.display-language");
    if (value === "zh-Hant" || value === "zh-Hans" || value === "en" || value === "ja" || value === "ko") return value;
    const legacy = window.localStorage.getItem("zhaowu.locale");
    if (legacy === "zh-Hans" || legacy === "en") return legacy;
  } catch {
    /* ignore */
  }
  return "zh-Hant";
}

function applyLanguage(language: DisplayLanguage) {
  const baseLocale = engineLocaleFor(language);
  useI18n.getState().setLocale(baseLocale);
  if (language === "ja") {
    useI18n.setState({ t: (key) => JA[key] ?? BASE_TRANSLATOR(key) });
  } else if (language === "ko") {
    useI18n.setState({ t: (key) => KO[key] ?? BASE_TRANSLATOR(key) });
  } else {
    useI18n.setState({ t: BASE_TRANSLATOR });
  }
  if (typeof document !== "undefined") document.documentElement.lang = language;
}

type DisplayLanguageState = {
  language: DisplayLanguage;
  setLanguage: (language: DisplayLanguage) => void;
};

const initialLanguage = readDisplayLanguage();

export const useDisplayLanguage = create<DisplayLanguageState>((set) => ({
  language: initialLanguage,
  setLanguage: (language) => {
    try {
      window.localStorage.setItem("zhaowu.display-language", language);
    } catch {
      /* ignore */
    }
    applyLanguage(language);
    set({ language });
  },
}));

export function hydrateDisplayLanguage() {
  const language = readDisplayLanguage();
  applyLanguage(language);
  useDisplayLanguage.setState({ language });
}

if (typeof window !== "undefined") applyLanguage(initialLanguage);
