export type KoHiLanguage = "ko" | "hi";

type TranslationTable = Record<string, string>;

const KO: TranslationTable = {
  "TODAY · FOUR PILLARS": "오늘 · 사주팔자",
  "Today's rhythm": "오늘의 흐름",
  "Today’s rhythm": "오늘의 흐름",
  "Today's guidance": "오늘의 안내",
  "Today’s guidance": "오늘의 안내",
  "Current Four Pillars": "현재 사주팔자",
  "Good for": "오늘 하기 좋은 것",
  "Avoid": "피하면 좋은 것",
  "Daily spirit slip": "오늘의 영첨",
  "Today’s Spirit Slip": "오늘의 영첨",
  "Today's Spirit Slip": "오늘의 영첨",
  "Based on your saved birth profile + today’s rhythm": "저장된 출생 정보와 오늘의 흐름을 바탕으로",
  "Based on your saved birth profile + today's rhythm": "저장된 출생 정보와 오늘의 흐름을 바탕으로",
  "View today’s pillars & guidance": "오늘의 사주와 안내 보기",
  "View today's pillars & guidance": "오늘의 사주와 안내 보기",
  "Solar term": "절기",
  "Moon": "달의 위상",
  "YEAR": "년주",
  "MONTH": "월주",
  "DAY": "일주",
  "HOUR": "시주",
  "Lower": "낮음",
  "Active": "활발",
  "Steady": "안정",
  "Conserve your attention and finish calmly": "집중력을 아끼고 차분히 마무리하세요",
  "Choose a direction before you move": "움직이기 전에 방향부터 정하세요",
  "Move forward with a steady centre": "중심을 지키며 안정적으로 나아가세요",
  "Keep some capacity in reserve. Fewer well-finished things are enough today.": "여력을 남겨두세요. 오늘은 적게 하더라도 중요한 일을 제대로 마무리하면 충분합니다.",
  "There is momentum today; give it one clear direction and finish in sequence.": "오늘은 추진력이 있습니다. 방향을 하나로 정하고 순서대로 마무리하세요.",
  "The rhythm is steady. Narrow the priority list and leave room for the unexpected.": "흐름이 안정적입니다. 우선순위를 줄이고 예상 밖의 변화에 대비할 여유를 남기세요.",
  "finish one important task": "중요한 일 하나 마무리하기",
  "eat on time": "제때 식사하기",
  "tidy one small area": "작은 공간 하나 정리하기",
  "move one key task forward": "핵심 과제 하나 진전시키기",
  "speak clearly": "분명하게 말하기",
  "finish before adding more": "추가하기 전에 먼저 마무리하기",
  "focus on the core task": "핵심 과제에 집중하기",
  "keep plans simple": "계획을 단순하게 유지하기",
  "leave buffer time": "여유 시간 남기기",
  "overcommitting": "과도하게 약속하기",
  "late-night decisions": "늦은 밤 큰 결정하기",
  "absorbing other people’s urgency": "다른 사람의 조급함까지 떠안기",
  "absorbing other people's urgency": "다른 사람의 조급함까지 떠안기",
  "starting too many things": "너무 많은 일을 동시에 시작하기",
  "arguing from impulse": "충동적으로 다투기",
  "rushing commitments": "서둘러 약속하기",
  "constant switching": "계속 일을 바꿔 하기",
  "needless comparison": "불필요한 비교",
  "overexplaining": "과도하게 설명하기",
  "Sign in first to draw your daily spirit slip.": "먼저 로그인하면 오늘의 개인 영첨을 받을 수 있습니다.",
  "Complete your birth details on Zhaowu first, then return here to draw your personalised daily slip.": "먼저 소오에 출생 정보를 입력한 뒤 돌아와 개인 영첨을 받아보세요.",
  "Sign in": "로그인",
  "Add birth details": "출생 정보 입력",
  "Close": "닫기",
  "Hold Your Centre": "중심을 지키기",
  "Open With Response": "응답이 있는 곳을 열기",
  "Set Direction First": "방향부터 정하기",
  "Leave Some Space": "여백을 남기기",
  "Gather Your Focus": "마음을 한곳에 모으기",
  "You do not need more answers today. Protect the one thing that matters most and let the noise fall away.": "오늘은 더 많은 답을 찾지 않아도 됩니다. 가장 중요한 한 가지를 지키면 잡음은 자연스럽게 줄어듭니다.",
  "In relationships, guess less. In decisions, confirm first. Keep your own pace.": "관계에서는 추측을 줄이고, 결정하기 전에는 먼저 확인하세요. 자신의 속도를 지키는 것이 중요합니다.",
  "Some doors are not meant to be forced. Notice what is genuinely responding to you before you invest more.": "억지로 밀어 열 필요가 없는 문도 있습니다. 더 투자하기 전에 무엇이 실제로 응답하는지 살펴보세요.",
  "Observe first, then move closer. Put energy where there is a real answer back.": "먼저 관찰한 뒤 가까이 가세요. 실제 응답이 있는 곳에 에너지를 쓰는 것이 좋습니다.",
  "Speed is not the priority today. Once the direction is clear, movement becomes much easier.": "오늘은 속도보다 방향이 중요합니다. 방향이 분명해지면 움직임은 훨씬 쉬워집니다.",
  "For money, commitments or relationships, confirm the core conditions before acting on emotion.": "돈, 약속, 관계에서는 감정대로 움직이기 전에 핵심 조건부터 확인하세요.",
  "Empty space is useful today. Doing slightly less can preserve the judgement you need for the next move.": "오늘은 여백이 도움이 됩니다. 조금 덜 하는 것이 다음 선택에 필요한 판단력을 지켜줍니다.",
  "Keep your capacity for decisions only you can make; postpone what does not need to happen now.": "당신만 할 수 있는 결정에 힘을 남기고, 지금 당장 필요하지 않은 일은 미뤄도 됩니다.",
  "There can be many things outside you while you keep only one main line inside. Clarity comes from not gripping every answer at once.": "밖에서 많은 일이 벌어져도 마음속에는 한 줄의 중심만 남겨두세요. 모든 답을 한꺼번에 붙잡지 않을 때 선명해집니다.",
  "Finish, organise and close loops today. Do not add weight just to prove something.": "오늘은 마무리하고 정리하고 끝낼 일을 끝내세요. 무엇을 증명하려고 부담을 더하지 마세요.",
  "White Dew": "백로",
  "Start of Spring": "입춘",
  "Awakening of Insects": "경칩",
  "Clear and Bright": "청명",
  "Start of Summer": "입하",
  "Grain in Ear": "망종",
  "Minor Heat": "소서",
  "Start of Autumn": "입추",
  "Cold Dew": "한로",
  "Start of Winter": "입동",
  "Major Snow": "대설",
  "Minor Cold": "소한",

  "ZHAOWU · CONSULTATION": "소오 · 상담",
  "What would you like to understand now?": "지금 가장 알고 싶은 것은 무엇인가요?",
  "A direct answer first, followed by the chart evidence, timing, and practical choices.": "먼저 결론을 제시하고, 이어서 명식 근거와 시기, 실제 선택지를 설명합니다.",
  "Your question": "질문",
  "For example: Is this role worth continuing? What should I prioritise now?": "예: 이 일을 계속할 가치가 있나요? 지금 무엇을 우선해야 하나요?",
  "Reading order": "해석 순서",
  "Answer": "결론",
  "Evidence": "근거",
  "Timing": "시기",
  "SHARED RECORD": "공용 출생 정보",
  "Client details": "출생 정보",
  "Enter the birth record once. Every personal reading can reuse it.": "출생 정보는 한 번만 입력하면 됩니다. 모든 개인 분석에서 같은 정보를 사용합니다.",
  "ZI PING · FOUR PILLARS": "자평 · 사주팔자",
  "Four Pillars chart": "사주팔자 명식",
  "Calculated from the client details above.": "위의 출생 정보를 바탕으로 계산합니다.",
  "Complete the client details to preview the Four Pillars chart.": "출생 정보를 입력하면 사주팔자 명식을 미리 볼 수 있습니다.",
  "Client record saved": "출생 정보 저장됨",
  "The other personal readings will reuse this record.": "다른 개인 분석에서도 이 정보를 그대로 사용합니다.",
  "Edit details": "정보 수정",
  "The analysis will use the client record shown above.": "위에 표시된 출생 정보를 사용해 분석합니다.",
  "Begin analysis": "분석 시작",
  "Analysing…": "분석 중…",
  "Birth record": "출생 정보",

  "Seven personal readings": "일곱 가지 개인 분석",
  "One birth record, seven independent lenses. Open any volume to read its own analysis.": "하나의 출생 정보로 일곱 가지 관점을 각각 독립적으로 봅니다. 원하는 항목을 열어 해당 분석을 읽어보세요.",
  "Four Pillars · BaZi": "사주팔자 · BaZi",
  "structure, balance, timing, and the question in front of you": "구조, 균형, 시기와 지금 묻고 있는 문제",
  "Zi Wei Dou Shu": "자미두수",
  "palaces, relationships, work, wealth, and life phases": "궁위, 관계, 일, 재정과 인생 단계",
  "Western astrology": "서양 점성술",
  "Sun, Moon, Rising, aspects, and life areas": "태양, 달, 상승궁, 각과 삶의 영역",
  "Classical Indian astrology": "인도 고전 점성술",
  "classical karmic patterns; D60 needs an accurate birth minute": "고전적 카르마 구조; D60은 정확한 출생 분이 필요합니다",
  "Seven Luminaries": "칠정사여",
  "temperament, pressure response, rhythm, and timing": "기질, 압박 반응, 리듬과 시기",
  "Past & Present": "전생과 현생",
  "cultural symbolism for recurring habits and themes": "반복되는 습관과 주제를 문화적 상징으로 읽기",
  "Numerology": "수비학",
  "your life number, strengths, pressure points, and Master Number pattern": "생명수, 강점, 압박 지점과 마스터 넘버 패턴",
  "Add birth data": "출생 정보 입력",
  "View · birth time needed for full precision": "보기 · 정확한 해석에는 출생 시간이 필요합니다",
  "Open analysis": "분석 보기",
  "Open BaZi analysis": "사주 분석 보기",
  "Start BaZi analysis": "사주 분석 시작",
  "Light self-reflection": "가벼운 자기 탐색",
  "Optional short tests. Nothing expands until you choose it.": "원할 때만 여는 짧은 테스트입니다. 선택하기 전에는 내용을 펼치지 않습니다.",
  "Five-Element Scent Map": "오행 향기 지도",
  "sensory preference compared with five-element cultural imagery": "감각 취향을 오행의 문화적 상징과 비교",
  "Inner Animal × Guardian Beast": "내면의 동물 × 명식 수호수",
  "current personality strategy and instinctive response": "현재의 성격 전략과 본능적 반응",
  "Five-Element Function Test": "오행 기능 테스트",
  "which function you currently want to strengthen": "지금 강화하고 싶은 기능 확인",
  "Six Realms Habit Test": "육도 습관 테스트",
  "which everyday habit pattern is strongest now": "현재 가장 강한 일상 습관 패턴 확인",

  "Jade Dragon guide": "청옥룡 안내",
  "Choose a reading, a self-test, or reopen a report. I will take you straight there.": "분석이나 가벼운 테스트를 고르거나 이전 보고서를 다시 여세요. 바로 안내해 드립니다.",
  "For example: show my previous Zi Wei report": "예: 이전 자미두수 보고서를 보여줘",
  "Ask": "묻기",
  "Close guide": "안내 닫기",
  "Open Jade Dragon guide": "청옥룡 안내 열기",
  "Guide": "안내",
  "BaZi": "사주팔자",
  "Fun tests": "가벼운 테스트",
  "My history": "내 기록",
  "Reading navigation": "분석 안내",

  "ZHAOWU · ACCOUNT": "ZHAOWU · 계정",
  "Email": "이메일",
  "My Zhaowu": "나의 소오",
  "Zhaowu Owner Console": "소오 운영자 콘솔",
  "Reports": "보고서",
  "Recent reports": "최근 보고서",
  "Customer reports": "고객 보고서",
  "Search email / question": "이메일 / 질문 검색",
  "No reports yet.": "아직 보고서가 없습니다.",
  "Open": "열기",
  "Collapse": "접기",
  "Refresh": "새로고침",
  "Refresh console": "콘솔 새로고침",
  "Refreshing…": "새로고침 중…",
  "Refreshed": "새로고침됨",
  "Chart summary": "명식 요약",
  "Final answer source: saved version, no live recalculation": "최종 답변 출처: 저장된 버전, 실시간 재계산 없음",
  "Chart ready": "명식 준비됨",
  "Chart pending": "명식 생성 대기",
  "Final answer ready": "최종 답변 준비됨",
  "Final answer pending": "최종 답변 저장 대기",
  "Full report ready": "전체 보고서 준비됨",
  "Full report pending": "전체 보고서 생성 대기",

  "INDEPENDENT READING": "독립 분석",
  "An independent classical Indian reading. D60 is highly sensitive to the birth minute.": "인도 고전 점성술을 독립적으로 참고합니다. D60은 출생 분 단위의 정확도에 매우 민감합니다.",
  "A separate view through the Sun, Moon, Rising sign, aspects and life areas.": "태양, 달, 상승궁, 각과 삶의 영역을 통해 별도의 관점으로 봅니다.",
  "An independent palace-and-timing view of character, relationships, work, money and life phases.": "궁위와 시기를 기준으로 성격, 관계, 일, 재정과 인생 단계를 독립적으로 봅니다.",
  "A separate reading of temperament, rhythm, pressure response and timing.": "기질, 리듬, 압박 반응과 시기를 별도로 읽습니다.",
  "Cultural symbolism for recurring habits and themes, kept as an independent supporting layer.": "반복되는 습관과 주제를 문화적 상징으로 읽는 독립 보조 분석입니다.",
  "Dharma One-Palm Classic": "달마일장경",
  "Four-life symbolism and repeated habits carried into this life.": "네 생의 상징과 이번 생까지 반복되는 습관을 봅니다.",
  "Birth record for this volume": "이 분석에 사용하는 출생 정보",
  "This reading was generated from the same saved birth record": "저장된 같은 출생 정보를 사용해 분석했습니다",
  "No birth record yet. Add it once on the homepage and all six specialist readings can reuse it.": "아직 출생 정보가 없습니다. 홈에서 한 번 입력하면 여섯 가지 전문 분석이 함께 사용할 수 있습니다.",
  "Edit birth record": "출생 정보 수정",
  "Back to six readings": "전문 분석 목록으로",
  "Reading overview": "분석 개요",

  "Four Pillars of Destiny": "사주팔자",
  "Your birth chart — year, month, day and hour.": "년·월·일·시 네 기둥으로 구성된 출생 명식입니다.",
  "Heavenly stem": "천간",
  "Earthly branch": "지지",
  "Stem relationship": "십신 관계",
  "Hidden stems": "지장간",
  "Na Yin image": "납음 상징",
  "Twelve-stage cycle": "십이운성",
  "Empty branches": "공망",
  "Life palace": "명궁",
  "Ten-year luck cycles": "대운",
  "Birth time not known": "출생 시간 미상",
  "Chart details": "명식 세부 정보",
  "Birth time and a cycle-direction setting are needed to show luck cycles.": "대운을 표시하려면 출생 시간과 대운 진행 방향이 필요합니다.",
  "Na Yin and the twelve stages are traditional symbolic terms, not health or lifespan predictions.": "납음과 십이운성은 전통적 상징 체계이며 건강이나 수명을 예측하는 내용이 아닙니다.",
  "Birth-hour verification needed": "출생 시각 검증 필요",
  "Clock-time candidate": "시계 시각 후보",
  "True-solar candidate": "진태양시 후보",
  "True-solar correction crossed a two-hour branch boundary. Both candidates are retained for event-based verification; the working chart currently uses true solar time. Do not choose a chart from personality descriptions alone.": "진태양시 보정이 시진 경계를 넘었습니다. 두 후보를 모두 보존해 실제 사건으로 검증하며, 현재 작업 명식은 진태양시를 사용합니다. 성격 묘사만으로 명식을 선택하지 않습니다.",
  "ZHAOWU · BAZI": "ZHAOWU · 사주",

  "Overall summary": "전체 요약",
  "Body areas to watch": "몸에서 살펴볼 부분",
  "Zhaowu | Personal full report": "소오 | 개인 전체 보고서",
  "View full report": "전체 보고서 보기",
  "Preparing your full report…": "전체 보고서 정리 중…",
  "Saving…": "저장 중…",
  "Update saved report": "저장된 보고서 업데이트",
  "The full report is ready, but cloud sync failed temporarily. The report remains available on this page.": "전체 보고서는 준비되었지만 클라우드 동기화가 잠시 실패했습니다. 이 페이지에서 보고서는 계속 볼 수 있습니다.",
  "The full report could not be generated right now.": "현재 전체 보고서를 만들 수 없습니다.",
  "The full report has been saved to this record.": "전체 보고서가 이 기록에 저장되었습니다.",
  "Saving failed.": "저장에 실패했습니다.",
  "Your personal decree image has been generated and saved.": "개인 명고 이미지가 생성되어 저장되었습니다.",
  "Your matched gallery artwork has been saved.": "매칭된 갤러리 이미지가 저장되었습니다.",
  "The decree image could not be loaded. Your text answer and full report remain available.": "명고 이미지를 불러오지 못했습니다. 텍스트 답변과 전체 보고서는 그대로 볼 수 있습니다.",

  "Daily dress | Five-element colour": "오늘의 오행 컬러",
  "STONE · NOTES": "STONE · 노트",
  "Zhaowu · Notes on Life": "소오 · 삶의 노트",
  "Our mission is to scale intelligence to serve humanity": "우리의 목표는 지혜를 더 많은 사람에게 도움이 되도록 확장하는 것입니다",
  "Keep some capacity in reserve": "여력을 조금 남겨두세요",
  "Home": "홈",
  "Play music": "음악 재생",
  "Music playing": "음악 재생 중",
  "Zhaowu background music": "소오 배경 음악",
};

const HI: TranslationTable = {
  "TODAY · FOUR PILLARS": "आज · चार स्तंभ",
  "Today's rhythm": "आज की लय",
  "Today’s rhythm": "आज की लय",
  "Today's guidance": "आज का मार्गदर्शन",
  "Today’s guidance": "आज का मार्गदर्शन",
  "Current Four Pillars": "वर्तमान चार स्तंभ",
  "Good for": "आज के लिए अच्छा",
  "Avoid": "आज इससे बचें",
  "Daily spirit slip": "आज का आध्यात्मिक संकेत",
  "Today’s Spirit Slip": "आज का आध्यात्मिक संकेत",
  "Today's Spirit Slip": "आज का आध्यात्मिक संकेत",
  "Based on your saved birth profile + today’s rhythm": "आपकी सहेजी जन्म-जानकारी और आज की लय के आधार पर",
  "Based on your saved birth profile + today's rhythm": "आपकी सहेजी जन्म-जानकारी और आज की लय के आधार पर",
  "View today’s pillars & guidance": "आज के चार स्तंभ और मार्गदर्शन देखें",
  "View today's pillars & guidance": "आज के चार स्तंभ और मार्गदर्शन देखें",
  "Solar term": "सौर ऋतु",
  "Moon": "चंद्र अवस्था",
  "YEAR": "वर्ष स्तंभ",
  "MONTH": "माह स्तंभ",
  "DAY": "दिन स्तंभ",
  "HOUR": "घंटा स्तंभ",
  "Lower": "कम",
  "Active": "सक्रिय",
  "Steady": "स्थिर",
  "Conserve your attention and finish calmly": "अपनी ऊर्जा बचाएँ और शांत होकर काम पूरा करें",
  "Choose a direction before you move": "आगे बढ़ने से पहले दिशा तय करें",
  "Move forward with a steady centre": "स्थिर केंद्र के साथ आगे बढ़ें",
  "Keep some capacity in reserve. Fewer well-finished things are enough today.": "कुछ ऊर्जा बचाकर रखें। आज कम काम भी पर्याप्त है, यदि जरूरी काम अच्छी तरह पूरा हो।",
  "There is momentum today; give it one clear direction and finish in sequence.": "आज आगे बढ़ने की गति है। इसे एक स्पष्ट दिशा दें और काम क्रम से पूरा करें।",
  "The rhythm is steady. Narrow the priority list and leave room for the unexpected.": "आज की लय स्थिर है। प्राथमिकताएँ कम रखें और अचानक बदलाव के लिए थोड़ा समय बचाएँ।",
  "finish one important task": "एक जरूरी काम पूरा करें",
  "eat on time": "समय पर खाएँ",
  "tidy one small area": "एक छोटी जगह व्यवस्थित करें",
  "move one key task forward": "एक मुख्य काम आगे बढ़ाएँ",
  "speak clearly": "स्पष्ट बोलें",
  "finish before adding more": "नया जोड़ने से पहले पुराना पूरा करें",
  "focus on the core task": "मुख्य काम पर ध्यान दें",
  "keep plans simple": "योजना सरल रखें",
  "leave buffer time": "अतिरिक्त समय रखें",
  "overcommitting": "बहुत अधिक वादे करना",
  "late-night decisions": "देर रात बड़े फैसले करना",
  "absorbing other people’s urgency": "दूसरों की जल्दबाजी अपने ऊपर लेना",
  "absorbing other people's urgency": "दूसरों की जल्दबाजी अपने ऊपर लेना",
  "starting too many things": "बहुत से काम एक साथ शुरू करना",
  "arguing from impulse": "आवेग में बहस करना",
  "rushing commitments": "जल्दबाजी में वादा करना",
  "constant switching": "बार-बार काम बदलना",
  "needless comparison": "बेकार तुलना",
  "overexplaining": "जरूरत से ज्यादा समझाना",
  "Sign in first to draw your daily spirit slip.": "आज का निजी संकेत पाने के लिए पहले साइन इन करें।",
  "Complete your birth details on Zhaowu first, then return here to draw your personalised daily slip.": "पहले झाओवू में अपनी जन्म-जानकारी पूरी करें, फिर यहाँ लौटकर निजी संकेत लें।",
  "Sign in": "साइन इन",
  "Add birth details": "जन्म-जानकारी भरें",
  "Close": "बंद करें",
  "Hold Your Centre": "अपना केंद्र संभालें",
  "Open With Response": "जहाँ उत्तर मिले वहीं खुलें",
  "Set Direction First": "पहले दिशा तय करें",
  "Leave Some Space": "थोड़ी जगह छोड़ें",
  "Gather Your Focus": "ध्यान समेटें",
  "You do not need more answers today. Protect the one thing that matters most and let the noise fall away.": "आज आपको और उत्तर खोजने की जरूरत नहीं। जो सबसे महत्वपूर्ण है उसे संभालें और बाकी शोर को जाने दें।",
  "In relationships, guess less. In decisions, confirm first. Keep your own pace.": "रिश्तों में कम अनुमान लगाएँ। फैसलों में पहले पुष्टि करें। अपनी गति बनाए रखें।",
  "Some doors are not meant to be forced. Notice what is genuinely responding to you before you invest more.": "कुछ दरवाजे जोर लगाकर खोलने के लिए नहीं होते। अधिक निवेश से पहले देखें कि सच में कहाँ से उत्तर मिल रहा है।",
  "Observe first, then move closer. Put energy where there is a real answer back.": "पहले देखें, फिर आगे बढ़ें। अपनी ऊर्जा वहीं लगाएँ जहाँ वास्तविक उत्तर मिल रहा हो।",
  "Speed is not the priority today. Once the direction is clear, movement becomes much easier.": "आज गति से अधिक दिशा महत्वपूर्ण है। दिशा साफ होते ही आगे बढ़ना आसान होगा।",
  "For money, commitments or relationships, confirm the core conditions before acting on emotion.": "पैसे, वादों या रिश्तों में भावना से कदम उठाने से पहले मूल शर्तें स्पष्ट करें।",
  "Empty space is useful today. Doing slightly less can preserve the judgement you need for the next move.": "आज थोड़ा खाली समय उपयोगी है। थोड़ा कम करने से अगला कदम तय करने की समझ बनी रहती है।",
  "Keep your capacity for decisions only you can make; postpone what does not need to happen now.": "अपनी ऊर्जा उन फैसलों के लिए बचाएँ जो केवल आप ले सकते हैं; बाकी को बाद में किया जा सकता है।",
  "There can be many things outside you while you keep only one main line inside. Clarity comes from not gripping every answer at once.": "बाहर बहुत कुछ चल सकता है, पर भीतर एक मुख्य दिशा रखें। हर उत्तर को एक साथ पकड़ने की जरूरत नहीं।",
  "Finish, organise and close loops today. Do not add weight just to prove something.": "आज काम पूरा करें, व्यवस्थित करें और अधूरे चक्र बंद करें। केवल साबित करने के लिए अतिरिक्त बोझ न लें।",
  "White Dew": "श्वेत ओस",
  "Start of Spring": "वसंत आरंभ",
  "Awakening of Insects": "कीट जागरण",
  "Clear and Bright": "निर्मल प्रकाश",
  "Start of Summer": "ग्रीष्म आरंभ",
  "Grain in Ear": "अनाज की बाली",
  "Minor Heat": "हल्की गर्मी",
  "Start of Autumn": "शरद आरंभ",
  "Cold Dew": "शीत ओस",
  "Start of Winter": "शीत ऋतु आरंभ",
  "Major Snow": "भारी हिम",
  "Minor Cold": "हल्की सर्दी",

  "ZHAOWU · CONSULTATION": "झाओवू · परामर्श",
  "What would you like to understand now?": "अभी आप सबसे अधिक क्या समझना चाहते हैं?",
  "A direct answer first, followed by the chart evidence, timing, and practical choices.": "पहले सीधा उत्तर, फिर कुंडली के आधार, समय और व्यावहारिक विकल्प।",
  "Your question": "आपका प्रश्न",
  "For example: Is this role worth continuing? What should I prioritise now?": "उदाहरण: क्या यह काम जारी रखना सही है? मुझे अभी किसे प्राथमिकता देनी चाहिए?",
  "Reading order": "विश्लेषण क्रम",
  "Answer": "उत्तर",
  "Evidence": "आधार",
  "Timing": "समय",
  "SHARED RECORD": "साझा जन्म-जानकारी",
  "Client details": "जन्म-जानकारी",
  "Enter the birth record once. Every personal reading can reuse it.": "जन्म-जानकारी केवल एक बार भरें। हर व्यक्तिगत विश्लेषण इसी जानकारी का उपयोग कर सकता है।",
  "ZI PING · FOUR PILLARS": "ज़ि पिंग · चार स्तंभ",
  "Four Pillars chart": "चार स्तंभ कुंडली",
  "Calculated from the client details above.": "ऊपर दी गई जन्म-जानकारी से गणना की गई।",
  "Complete the client details to preview the Four Pillars chart.": "जन्म-जानकारी पूरी करने पर यहाँ चार स्तंभ कुंडली दिखाई देगी।",
  "Client record saved": "जन्म-जानकारी सहेजी गई",
  "The other personal readings will reuse this record.": "दूसरे व्यक्तिगत विश्लेषण भी इसी जानकारी का उपयोग करेंगे।",
  "Edit details": "जानकारी बदलें",
  "The analysis will use the client record shown above.": "विश्लेषण ऊपर दिखाई गई जन्म-जानकारी का उपयोग करेगा।",
  "Begin analysis": "विश्लेषण शुरू करें",
  "Analysing…": "विश्लेषण हो रहा है…",
  "Birth record": "जन्म-जानकारी",

  "Seven personal readings": "सात व्यक्तिगत विश्लेषण",
  "One birth record, seven independent lenses. Open any volume to read its own analysis.": "एक जन्म-जानकारी, सात स्वतंत्र दृष्टिकोण। किसी भी खंड को खोलकर उसका विश्लेषण पढ़ें।",
  "Four Pillars · BaZi": "चार स्तंभ · BaZi",
  "structure, balance, timing, and the question in front of you": "संरचना, संतुलन, समय और आपका वर्तमान प्रश्न",
  "Zi Wei Dou Shu": "ज़ी वेई डोउ शू",
  "palaces, relationships, work, wealth, and life phases": "जीवन क्षेत्र, रिश्ते, काम, धन और जीवन चरण",
  "Western astrology": "पश्चिमी ज्योतिष",
  "Sun, Moon, Rising, aspects, and life areas": "सूर्य, चंद्र, लग्न, ग्रह संबंध और जीवन क्षेत्र",
  "Classical Indian astrology": "शास्त्रीय भारतीय ज्योतिष",
  "classical karmic patterns; D60 needs an accurate birth minute": "शास्त्रीय कर्म पैटर्न; D60 के लिए जन्म का सही मिनट आवश्यक है",
  "Seven Luminaries": "सात ग्रह पद्धति",
  "temperament, pressure response, rhythm, and timing": "स्वभाव, दबाव की प्रतिक्रिया, लय और समय",
  "Past & Present": "पूर्वजन्म और वर्तमान",
  "cultural symbolism for recurring habits and themes": "दोहराती आदतों और विषयों का सांस्कृतिक प्रतीकात्मक अध्ययन",
  "Numerology": "अंक ज्योतिष",
  "your life number, strengths, pressure points, and Master Number pattern": "जीवन अंक, ताकतें, दबाव के बिंदु और मास्टर नंबर पैटर्न",
  "Add birth data": "जन्म-जानकारी भरें",
  "View · birth time needed for full precision": "देखें · पूर्ण सटीकता के लिए जन्म समय आवश्यक है",
  "Open analysis": "विश्लेषण खोलें",
  "Open BaZi analysis": "चार स्तंभ विश्लेषण खोलें",
  "Start BaZi analysis": "चार स्तंभ विश्लेषण शुरू करें",
  "Light self-reflection": "हल्का आत्म-चिंतन",
  "Optional short tests. Nothing expands until you choose it.": "छोटे वैकल्पिक परीक्षण। जब तक आप चुनें नहीं, कोई भाग नहीं खुलेगा।",
  "Five-Element Scent Map": "पाँच-तत्व सुगंध मानचित्र",
  "sensory preference compared with five-element cultural imagery": "इंद्रिय पसंद की तुलना पाँच-तत्व सांस्कृतिक प्रतीकों से",
  "Inner Animal × Guardian Beast": "आंतरिक पशु × रक्षक प्रतीक",
  "current personality strategy and instinctive response": "वर्तमान व्यक्तित्व रणनीति और सहज प्रतिक्रिया",
  "Five-Element Function Test": "पाँच-तत्व कार्य परीक्षण",
  "which function you currently want to strengthen": "अभी किस क्षमता को मजबूत करना चाहते हैं",
  "Six Realms Habit Test": "छह लोक आदत परीक्षण",
  "which everyday habit pattern is strongest now": "अभी कौन-सा दैनिक आदत पैटर्न सबसे मजबूत है",

  "Jade Dragon guide": "जेड ड्रैगन मार्गदर्शक",
  "Choose a reading, a self-test, or reopen a report. I will take you straight there.": "कोई विश्लेषण या छोटा परीक्षण चुनें, या पुरानी रिपोर्ट खोलें। मैं आपको सीधे वहाँ ले जाऊँगा।",
  "For example: show my previous Zi Wei report": "उदाहरण: मेरी पिछली ज़ी वेई रिपोर्ट दिखाएँ",
  "Ask": "पूछें",
  "Close guide": "मार्गदर्शक बंद करें",
  "Open Jade Dragon guide": "जेड ड्रैगन मार्गदर्शक खोलें",
  "Guide": "मार्गदर्शक",
  "BaZi": "चार स्तंभ",
  "Fun tests": "हल्के परीक्षण",
  "My history": "मेरे रिकॉर्ड",
  "Reading navigation": "विश्लेषण नेविगेशन",

  "ZHAOWU · ACCOUNT": "ZHAOWU · खाता",
  "Email": "ईमेल",
  "My Zhaowu": "मेरा झाओवू",
  "Zhaowu Owner Console": "झाओवू स्वामी कंसोल",
  "Reports": "रिपोर्ट",
  "Recent reports": "हाल की रिपोर्ट",
  "Customer reports": "ग्राहक रिपोर्ट",
  "Search email / question": "ईमेल / प्रश्न खोजें",
  "No reports yet.": "अभी कोई रिपोर्ट नहीं है।",
  "Open": "खोलें",
  "Collapse": "समेटें",
  "Refresh": "ताज़ा करें",
  "Refresh console": "कंसोल ताज़ा करें",
  "Refreshing…": "ताज़ा हो रहा है…",
  "Refreshed": "ताज़ा किया गया",
  "Chart summary": "कुंडली सारांश",
  "Final answer source: saved version, no live recalculation": "अंतिम उत्तर स्रोत: सहेजा गया संस्करण, लाइव पुनर्गणना नहीं",
  "Chart ready": "कुंडली तैयार",
  "Chart pending": "कुंडली लंबित",
  "Final answer ready": "अंतिम उत्तर तैयार",
  "Final answer pending": "अंतिम उत्तर लंबित",
  "Full report ready": "पूरी रिपोर्ट तैयार",
  "Full report pending": "पूरी रिपोर्ट लंबित",

  "INDEPENDENT READING": "स्वतंत्र विश्लेषण",
  "An independent classical Indian reading. D60 is highly sensitive to the birth minute.": "शास्त्रीय भारतीय ज्योतिष का स्वतंत्र पूरक विश्लेषण। D60 जन्म के सही मिनट के प्रति बहुत संवेदनशील है।",
  "A separate view through the Sun, Moon, Rising sign, aspects and life areas.": "सूर्य, चंद्र, लग्न, ग्रह संबंध और जीवन क्षेत्रों से अलग दृष्टिकोण।",
  "An independent palace-and-timing view of character, relationships, work, money and life phases.": "जीवन क्षेत्रों और समय के आधार पर स्वभाव, रिश्ते, काम, धन और जीवन चरणों का स्वतंत्र अध्ययन।",
  "A separate reading of temperament, rhythm, pressure response and timing.": "स्वभाव, लय, दबाव की प्रतिक्रिया और समय का स्वतंत्र विश्लेषण।",
  "Cultural symbolism for recurring habits and themes, kept as an independent supporting layer.": "दोहराती आदतों और विषयों का सांस्कृतिक प्रतीकात्मक अध्ययन, एक स्वतंत्र पूरक स्तर के रूप में।",
  "Dharma One-Palm Classic": "धर्म वन-पाम क्लासिक",
  "Four-life symbolism and repeated habits carried into this life.": "चार जीवनों के प्रतीक और इस जीवन तक चली आई दोहराती आदतें।",
  "Birth record for this volume": "इस विश्लेषण की जन्म-जानकारी",
  "This reading was generated from the same saved birth record": "यह विश्लेषण उसी सहेजी जन्म-जानकारी से बनाया गया है",
  "No birth record yet. Add it once on the homepage and all six specialist readings can reuse it.": "अभी जन्म-जानकारी नहीं है। होम पेज पर एक बार भरें; सभी छह विशेष विश्लेषण इसका उपयोग कर सकेंगे।",
  "Edit birth record": "जन्म-जानकारी बदलें",
  "Back to six readings": "विशेष विश्लेषण सूची पर लौटें",
  "Reading overview": "विश्लेषण सारांश",

  "Four Pillars of Destiny": "चार स्तंभ कुंडली",
  "Your birth chart — year, month, day and hour.": "आपकी जन्म कुंडली — वर्ष, माह, दिन और समय के चार स्तंभ।",
  "Heavenly stem": "स्वर्गीय तना",
  "Earthly branch": "पार्थिव शाखा",
  "Stem relationship": "तत्व संबंध",
  "Hidden stems": "छिपे तने",
  "Na Yin image": "ना यिन प्रतीक",
  "Twelve-stage cycle": "बारह-अवस्था चक्र",
  "Empty branches": "रिक्त शाखाएँ",
  "Life palace": "जीवन महल",
  "Ten-year luck cycles": "दस-वर्षीय भाग्य चक्र",
  "Birth time not known": "जन्म समय अज्ञात",
  "Chart details": "कुंडली विवरण",
  "Birth time and a cycle-direction setting are needed to show luck cycles.": "भाग्य चक्र दिखाने के लिए जन्म समय और चक्र दिशा आवश्यक है।",
  "Na Yin and the twelve stages are traditional symbolic terms, not health or lifespan predictions.": "ना यिन और बारह अवस्थाएँ पारंपरिक प्रतीकात्मक शब्द हैं; ये स्वास्थ्य या आयु की भविष्यवाणी नहीं हैं।",
  "Birth-hour verification needed": "जन्म समय सत्यापन आवश्यक",
  "Clock-time candidate": "घड़ी-समय विकल्प",
  "True-solar candidate": "सच्चे सौर समय का विकल्प",
  "True-solar correction crossed a two-hour branch boundary. Both candidates are retained for event-based verification; the working chart currently uses true solar time. Do not choose a chart from personality descriptions alone.": "सच्चे सौर समय के सुधार ने दो-घंटे की सीमा पार की है। दोनों विकल्प वास्तविक घटनाओं से सत्यापन के लिए रखे गए हैं; वर्तमान कार्य-कुंडली सच्चे सौर समय का उपयोग करती है। केवल व्यक्तित्व विवरण के आधार पर कुंडली न चुनें।",
  "ZHAOWU · BAZI": "ZHAOWU · चार स्तंभ",

  "Overall summary": "समग्र सारांश",
  "Body areas to watch": "शरीर में ध्यान देने वाले भाग",
  "Zhaowu | Personal full report": "झाओवू | व्यक्तिगत पूरी रिपोर्ट",
  "View full report": "पूरी रिपोर्ट देखें",
  "Preparing your full report…": "पूरी रिपोर्ट तैयार की जा रही है…",
  "Saving…": "सहेजा जा रहा है…",
  "Update saved report": "सहेजी रिपोर्ट अपडेट करें",
  "The full report is ready, but cloud sync failed temporarily. The report remains available on this page.": "पूरी रिपोर्ट तैयार है, लेकिन क्लाउड सिंक अस्थायी रूप से विफल हुआ। रिपोर्ट इस पेज पर उपलब्ध है।",
  "The full report could not be generated right now.": "इस समय पूरी रिपोर्ट तैयार नहीं हो सकी।",
  "The full report has been saved to this record.": "पूरी रिपोर्ट इस रिकॉर्ड में सहेजी गई है।",
  "Saving failed.": "सहेजना विफल हुआ।",
  "Your personal decree image has been generated and saved.": "आपकी व्यक्तिगत चित्र-रचना बनाई और सहेजी गई है।",
  "Your matched gallery artwork has been saved.": "आपसे मेल खाती गैलरी छवि सहेजी गई है।",
  "The decree image could not be loaded. Your text answer and full report remain available.": "चित्र लोड नहीं हो सका। आपका लिखित उत्तर और पूरी रिपोर्ट उपलब्ध हैं।",

  "Daily dress | Five-element colour": "आज के पाँच-तत्व रंग",
  "STONE · NOTES": "STONE · नोट्स",
  "Zhaowu · Notes on Life": "झाओवू · जीवन नोट्स",
  "Our mission is to scale intelligence to serve humanity": "हमारा उद्देश्य बुद्धिमत्ता को मानवता की सेवा के लिए व्यापक बनाना है",
  "Keep some capacity in reserve": "कुछ ऊर्जा बचाकर रखें",
  "Home": "होम",
  "Play music": "संगीत चलाएँ",
  "Music playing": "संगीत चल रहा है",
  "Zhaowu background music": "झाओवू पृष्ठभूमि संगीत",
};

const WEEKDAYS = {
  ko: { Sunday: "일요일", Monday: "월요일", Tuesday: "화요일", Wednesday: "수요일", Thursday: "목요일", Friday: "금요일", Saturday: "토요일" },
  hi: { Sunday: "रविवार", Monday: "सोमवार", Tuesday: "मंगलवार", Wednesday: "बुधवार", Thursday: "गुरुवार", Friday: "शुक्रवार", Saturday: "शनिवार" },
} as const;

const MONTHS = {
  ko: { January: "1월", February: "2월", March: "3월", April: "4월", May: "5월", June: "6월", July: "7월", August: "8월", September: "9월", October: "10월", November: "11월", December: "12월" },
  hi: { January: "जनवरी", February: "फ़रवरी", March: "मार्च", April: "अप्रैल", May: "मई", June: "जून", July: "जुलाई", August: "अगस्त", September: "सितंबर", October: "अक्टूबर", November: "नवंबर", December: "दिसंबर" },
} as const;

const PREFIXES = {
  ko: [
    ["Pause background music: ", "배경 음악 일시정지: "],
    ["Play background music: ", "배경 음악 재생: "],
    ["Current solar-term month: ", "현재 절기 월: "],
    ["Chart guardian beast: ", "명식 수호수: "],
    ["Shortlist: ", "우선 후보: "],
  ],
  hi: [
    ["Pause background music: ", "पृष्ठभूमि संगीत रोकें: "],
    ["Play background music: ", "पृष्ठभूमि संगीत चलाएँ: "],
    ["Current solar-term month: ", "वर्तमान सौर-ऋतु माह: "],
    ["Chart guardian beast: ", "कुंडली रक्षक प्रतीक: "],
    ["Shortlist: ", "प्राथमिक विकल्प: "],
  ],
} as const;

function preserveSpace(original: string, translated: string) {
  const leading = original.match(/^\s*/)?.[0] ?? "";
  const trailing = original.match(/\s*$/)?.[0] ?? "";
  return `${leading}${translated}${trailing}`;
}

function translateDate(value: string, language: KoHiLanguage): string | null {
  const match = value.match(/^(Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday)\s+(\d{1,2})\s+(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{4})$/);
  if (!match) return null;
  const [, weekday, day, month, year] = match;
  if (language === "ko") return `${year}년 ${MONTHS.ko[month as keyof typeof MONTHS.ko]} ${day}일 ${WEEKDAYS.ko[weekday as keyof typeof WEEKDAYS.ko]}`;
  return `${WEEKDAYS.hi[weekday as keyof typeof WEEKDAYS.hi]}, ${day} ${MONTHS.hi[month as keyof typeof MONTHS.hi]} ${year}`;
}

export function translateKoHiVisibleText(value: string, language: KoHiLanguage): string {
  if (!value.trim()) return value;
  const core = value.trim();
  const table = language === "ko" ? KO : HI;
  const exact = table[core];
  if (exact) return preserveSpace(value, exact);
  const date = translateDate(core, language);
  if (date) return preserveSpace(value, date);

  let next = core;
  for (const [prefix, translated] of PREFIXES[language]) {
    if (next.startsWith(prefix)) {
      next = `${translated}${next.slice(prefix.length)}`;
      break;
    }
  }

  for (const [english, translated] of Object.entries(table).sort((a, b) => b[0].length - a[0].length)) {
    if (english.length < 5 || !next.includes(english)) continue;
    next = next.split(english).join(translated);
  }

  const weekdays = WEEKDAYS[language];
  const months = MONTHS[language];
  for (const [english, translated] of Object.entries(weekdays)) next = next.replace(new RegExp(`\\b${english}\\b`, "g"), translated);
  for (const [english, translated] of Object.entries(months)) next = next.replace(new RegExp(`\\b${english}\\b`, "g"), translated);
  return preserveSpace(value, next);
}

export function hasUntranslatedCoreEnglish(value: string): boolean {
  const text = value.trim();
  if (!text) return false;
  if (/^(ZHAOWU|STONE|BaZi|D60|Email|https?:|[\w.+-]+@[\w.-]+)$/i.test(text)) return false;
  const words = text.match(/[A-Za-z]{3,}/g) ?? [];
  return words.length >= 3;
}
