import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { createRouter, RouterProvider } from '@tanstack/react-router';
import { routeTree } from './routeTree.gen';
import './styles.css';
import './intro-extra.css';
import './emblems.css';
import './client-hotfix.css';
import './visual-refresh.css';
import './stone-visual-fix.css';
import './motif-row-lock.css';
import './focused-report.css';
import './character-panel.css';
import './login-breathing.css';
import './palm-light-refinement.css';
import './wallpaper-visibility-fix.css';
import './green-dragon-guide.css';
import './report-history.css';
import './tea-guardian.css';
import './landscape-paper.css';
import './production-visual-reset.css';
import './gallery-unification.css';
import './approved-mobile-ui-v2.css';
import './approved-parchment-ui-v3.css';
import './visual-readability-lock-v4.css';
import './home-sheet-ui-v5.css';
import './typography-lock-v6.css';
import './home-quiz-paper.css';
import './content-layout-fixes.css';
import './parchment-layout.css';
import './zhaowu-paper-reference-v31.css';
import './ios-section-visibility.css';
import './report-visual-book.css';
import './report-luck-book.css';
import './report-visual-assets.css';
import './report-share-card.css';

const router = createRouter({ routeTree });
declare module '@tanstack/react-router' { interface Register { router: typeof router; } }
const root = document.getElementById('root');
if (!root) throw new Error('Missing root element');
if ('serviceWorker' in navigator) { window.addEventListener('load', () => { void navigator.serviceWorker.register('/sw.js', { scope: '/' }).catch(() => undefined); }); }
createRoot(root).render(<StrictMode><RouterProvider router={router} /></StrictMode>);
