/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TianjiXinggongRouteImport } from './routes/tianji-xinggong'
import { Route as YizhangjingRouteImport } from './routes/yizhangjing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TianjiXinggongRoute = TianjiXinggongRouteImport.update({
  id: '/tianji-xinggong',
  path: '/tianji-xinggong',
  getParentRoute: () => rootRouteImport,
} as any)
const YizhangjingRoute = YizhangjingRouteImport.update({
  id: '/yizhangjing',
  path: '/yizhangjing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/tianji-xinggong': typeof TianjiXinggongRoute
  '/yizhangjing': typeof YizhangjingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/tianji-xinggong': typeof TianjiXinggongRoute
  '/yizhangjing': typeof YizhangjingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/tianji-xinggong': typeof TianjiXinggongRoute
  '/yizhangjing': typeof YizhangjingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/account' | '/login' | '/tianji-xinggong' | '/yizhangjing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/login' | '/tianji-xinggong' | '/yizhangjing'
  id: '__root__' | '/' | '/account' | '/login' | '/tianji-xinggong' | '/yizhangjing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  LoginRoute: typeof LoginRoute
  TianjiXinggongRoute: typeof TianjiXinggongRoute
  YizhangjingRoute: typeof YizhangjingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tianji-xinggong': {
      id: '/tianji-xinggong'
      path: '/tianji-xinggong'
      fullPath: '/tianji-xinggong'
      preLoaderRoute: typeof TianjiXinggongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yizhangjing': {
      id: '/yizhangjing'
      path: '/yizhangjing'
      fullPath: '/yizhangjing'
      preLoaderRoute: typeof YizhangjingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  LoginRoute: LoginRoute,
  TianjiXinggongRoute: TianjiXinggongRoute,
  YizhangjingRoute: YizhangjingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
